import com.google.common.base.Charsets;
import org.skife.config.CommonsConfigSource;
import org.skife.config.Default;
import org.skife.config.Config;
import org.skife.config.ConfigurationObjectFactory;
import org.apache.commons.configuration.PropertiesConfiguration;
import java.util.Properties;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        Properties properties = new Properties();
        properties.setProperty("key","this is a key");
        PropertiesConfiguration pc = new PropertiesConfiguration();
        pc.setEncoding(Charsets.UTF_8.name());
        pc.setDelimiterParsingDisabled(true);
        CommonsConfigSource ccs = new CommonsConfigSource(pc);
        ConfigurationObjectFactory factory = new ConfigurationObjectFactory(ccs);
        //ConfigurationObjectFactory factory = new ConfigurationObjectFactory(properties);
        MyConfig config = factory.build(MyConfig.class);
        System.out.println(config.getStuff());
    }
}
